# Generated by Django 4.2.2 on 2023-07-02 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombrar', max_length=300, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='Sin especificar ', max_length=300, verbose_name='Descripción')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('fecha_registro', models.DateField(default=datetime.date(2023, 7, 2), verbose_name='Fecha de registro')),
            ],
        ),
    ]
