# Generated by Django 4.2.2 on 2023-07-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estatus',
            field=models.BooleanField(choices=[('D', 'Disponible'), ('ND', 'No Disponible')], default=False, verbose_name='Estatus'),
        ),
    ]
