# Generated by Django 4.2.2 on 2023-07-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_estatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estatus',
            field=models.BooleanField(choices=[(True, 'Disponible'), (False, 'No Disponible')], default=False, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
